# fastanime/core/config/defaults.py

from ..constants import APP_DATA_DIR, APP_NAME, USER_VIDEOS_DIR

# GeneralConfig
GENERAL_PYGMENT_STYLE = "github-dark"
GENERAL_API_CLIENT = "anilist"
GENERAL_PROVIDER = "allanime"
GENERAL_SELECTOR = "default"
GENERAL_AUTO_SELECT_ANIME_RESULT = True
GENERAL_ICONS = False
GENERAL_PREVIEW = "none"
GENERAL_IMAGE_RENDERER = "chafa"
GENERAL_MANGA_VIEWER = "feh"
GENERAL_CHECK_FOR_UPDATES = True
GENERAL_CACHE_REQUESTS = True
GENERAL_MAX_CACHE_LIFETIME = "03:00:00"
GENERAL_NORMALIZE_TITLES = True
GENERAL_DISCORD = False
GENERAL_RECENT = 50

# StreamConfig
STREAM_PLAYER = "mpv"
STREAM_QUALITY = "1080"
STREAM_TRANSLATION_TYPE = "sub"
STREAM_SERVER = "TOP"
STREAM_AUTO_NEXT = False
STREAM_CONTINUE_FROM_WATCH_HISTORY = True
STREAM_PREFERRED_WATCH_HISTORY = "local"
STREAM_AUTO_SKIP = False
STREAM_EPISODE_COMPLETE_AT = 80
STREAM_YTDLP_FORMAT = "best[height<=1080]/bestvideo[height<=1080]+bestaudio/best"
STREAM_FORCE_FORWARD_TRACKING = True
STREAM_DEFAULT_MEDIA_LIST_TRACKING = "prompt"
STREAM_SUB_LANG = "eng"

# ServiceConfig
SERVICE_ENABLED = False
SERVICE_WATCHLIST_CHECK_INTERVAL = 30
SERVICE_QUEUE_PROCESS_INTERVAL = 1
SERVICE_MAX_CONCURRENT_DOWNLOADS = 3
SERVICE_AUTO_RETRY_COUNT = 3
SERVICE_CLEANUP_COMPLETED_DAYS = 7
SERVICE_NOTIFICATION_ENABLED = True

# FzfConfig
FZF_HEADER_COLOR = "95,135,175"
FZF_PREVIEW_HEADER_COLOR = "215,0,95"
FZF_PREVIEW_SEPARATOR_COLOR = "208,208,208"

# MpvConfig
MPV_ARGS = ""
MPV_PRE_ARGS = ""
MPV_DISABLE_POPEN = True
MPV_USE_PYTHON_MPV = False

# VlcConfig
VLC_ARGS = ""

# AnilistConfig
ANILIST_PER_PAGE = 15
ANILIST_SORT_BY = "SEARCH_MATCH"
ANILIST_PREFERRED_LANGUAGE = "english"

# DownloadsConfig
DOWNLOADS_DOWNLOADER = "auto"
DOWNLOADS_DOWNLOADS_DIR = USER_VIDEOS_DIR
DOWNLOADS_ENABLE_TRACKING = True
DOWNLOADS_AUTO_ORGANIZE = True
DOWNLOADS_MAX_CONCURRENT = 3
DOWNLOADS_AUTO_CLEANUP_FAILED = True
DOWNLOADS_RETENTION_DAYS = 30
DOWNLOADS_SYNC_WITH_WATCH_HISTORY = True
DOWNLOADS_AUTO_MARK_OFFLINE = True
DOWNLOADS_NAMING_TEMPLATE = "{title}/Season {season:02d}/{episode:02d} - {episode_title}.{ext}"
DOWNLOADS_PREFERRED_QUALITY = "1080"
DOWNLOADS_DOWNLOAD_SUBTITLES = True
DOWNLOADS_SUBTITLE_LANGUAGES = ["en"]
DOWNLOADS_QUEUE_MAX_SIZE = 100
DOWNLOADS_AUTO_START_DOWNLOADS = True
DOWNLOADS_RETRY_ATTEMPTS = 3
DOWNLOADS_RETRY_DELAY = 300

# RegistryConfig
MEDIA_REGISTRY_DIR = USER_VIDEOS_DIR / APP_NAME / "registry"
MEDIA_REGISTRY_INDEX_DIR = APP_DATA_DIR