query ($id: Int) {
  Page {
    pageInfo {
      total
    }
    reviews(mediaId: $id) {
      summary
      user {
        name
        avatar {
          large
          medium
        }
      }
      body
    }
  }
}
