query ($type: MediaType, $page: Int, $perPage: Int) {
  Page(perPage: $perPage, page: $page) {
    media(sort: SCORE_DESC, type: $type, genre_not_in: ["hentai"]) {
      id
      idMal
      title {
        romaji
        english
      }
      coverImage {
        medium
        large
      }
      trailer {
        site
        id
      }
      mediaListEntry {
        status
        id
        progress
      }
      popularity
      streamingEpisodes {
        title
        thumbnail
      }
      episodes
      favourites
      averageScore
      description
      genres
      synonyms
      studios {
        nodes {
          name
          isAnimationStudio
        }
      }
      tags {
        name
      }
      startDate {
        year
        month
        day
      }
      endDate {
        year
        month
        day
      }
      status
      nextAiringEpisode {
        timeUntilAiring
        airingAt
        episode
      }
    }
  }
}
