query ($page: Int, $type: MediaType, $perPage: Int) {
  Page(perPage: $perPage, page: $page) {
    pageInfo {
      total
      perPage
      currentPage
      hasNextPage
    }
    media(
      type: $type
      status: NOT_YET_RELEASED
      sort: POPULARITY_DESC
      genre_not_in: ["hentai"]
    ) {
      id
      idMal
      title {
        romaji
        english
      }
      coverImage {
        medium
        large
      }
      trailer {
        site
        id
      }
      mediaListEntry {
        status
        id
        progress
      }
      popularity
      streamingEpisodes {
        title
        thumbnail
      }
      favourites
      averageScore
      genres
      synonyms
      episodes
      description
      studios {
        nodes {
          name
          isAnimationStudio
        }
      }
      tags {
        name
      }
      startDate {
        year
        month
        day
      }
      endDate {
        year
        month
        day
      }
      status
      nextAiringEpisode {
        timeUntilAiring
        airingAt
        episode
      }
    }
  }
}
