query (
  $userId: Int
  $status: MediaListStatus
  $type: MediaType
  $page: Int
  $perPage: Int
) {
  Page(perPage: $perPage, page: $page) {
    pageInfo {
      currentPage
      total
    }
    mediaList(userId: $userId, status: $status, type: $type) {
      mediaId
      media {
        id
        idMal
        title {
          romaji
          english
        }
        coverImage {
          medium
          large
        }
        trailer {
          site
          id
        }
        popularity
        streamingEpisodes {
          title
          thumbnail
        }
        favourites
        averageScore
        episodes
        genres
        synonyms
        studios {
          nodes {
            name
            isAnimationStudio
          }
        }
        tags {
          name
        }
        startDate {
          year
          month
          day
        }
        endDate {
          year
          month
          day
        }
        status
        description
        mediaListEntry {
          status
          id
          progress
        }
        nextAiringEpisode {
          timeUntilAiring
          airingAt
          episode
        }
      }
      status
      progress
      score
      repeat
      notes
      startedAt {
        year
        month
        day
      }
      completedAt {
        year
        month
        day
      }
      createdAt
    }
  }
}
